import * as fs from 'fs';
import * as path from 'path';
import { app, BrowserWindow, ipcMain } from 'electron';
import { autoUpdater, type Logger } from 'electron-updater';
import { IPC } from '../shared/ipc-channels';
import { trackEvent, sanitizeErrorMessage } from './analytics/analytics';
import { reportHandledError } from './analytics/error-reporting';
import { normalizeReleaseNotes } from './updater-release-notes';

const CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000; // 4 hours
const INITIAL_DELAY_MS = 5000; // 5 seconds after launch
const RETRY_DELAY_MS = 30_000; // 30 seconds before retry

let checkTimeout: ReturnType<typeof setTimeout> | null = null;
let checkInterval: ReturnType<typeof setInterval> | null = null;
let updaterWindow: BrowserWindow | null = null;
let checkRetrying = false;
let downloadRetrying = false;
/** Set once `notifyReadOnlyVolume` has told the user, for this app run only. */
let readOnlyVolumeNoticeSent = false;

/**
 * Path to the auto-updater manifest, generated by electron-builder when
 * `--publish` is set. On packaged builds it lives in the platform's resources
 * directory. Exported for testing.
 * @internal
 */
export function manifestPath(): string {
  return path.join(process.resourcesPath, 'app-update.yml');
}

function tagUpdaterLine(message: unknown): string {
  // breadcrumb-ok: electron-updater's own text (versions, feed URLs, cache paths), whose paths the policy redacts
  return `[electron-updater] ${String(message)}`;
}

/**
 * electron-updater's own log lines, which carry the Squirrel and package
 * manager detail behind most updater failures. Its default logger is the bare
 * console, whose untagged lines the Sentry breadcrumb policy drops
 * (src/shared/sentry-breadcrumbs.ts), so this tags them `[electron-updater]`,
 * which the policy keeps. Debug goes to console.debug, which the policy always
 * drops: a differential download's blockmap lines still reach the terminal but
 * no longer fill the breadcrumb ring. Each call reads `console` late so it goes
 * through whatever wrappers are installed by then. Exported for testing.
 * @internal
 */
export const updaterLogger: Logger = {
  info: (message?: unknown) => console.log(tagUpdaterLine(message)),
  warn: (message?: unknown) => console.warn(tagUpdaterLine(message)),
  error: (message?: unknown) => console.error(tagUpdaterLine(message)),
  debug: (message: string) => console.debug(tagUpdaterLine(message)),
};

/**
 * True when the auto-updater manifest is present at its expected location.
 * Exported for testing.
 * @internal
 */
export function manifestExists(): boolean {
  return fs.existsSync(manifestPath());
}

/**
 * Returns true if the error is a known-transient download/network failure
 * that should not surface as `app_error` telemetry. Structural failures
 * (signature mismatch, bad manifest, disk full, permission denied, 4xx
 * client errors) still propagate so real bugs stay visible.
 */
export function isTransientUpdaterError(error: Error): boolean {
  const errorCode = (error as NodeJS.ErrnoException).code;
  const errorMessage = error.message ?? '';

  if (errorCode === 'ECONNRESET' || errorCode === 'ETIMEDOUT'
      || errorCode === 'EAI_AGAIN' || errorCode === 'ENOTFOUND'
      || errorCode === 'ENETUNREACH' || errorCode === 'EPIPE') {
    return true;
  }

  if (errorCode && /^HTTP_ERROR_(5\d\d|408|429|618)$/.test(errorCode)) {
    return true;
  }

  if (/net::ERR_/.test(errorMessage)) return true;
  if (/Request has been aborted by the server/i.test(errorMessage)) return true;
  if (/Cannot pipe ".*":/i.test(errorMessage)) return true;

  return false;
}

/**
 * The two electron-updater wrappers that swallow a releases-feed fetch failure.
 * GitHubProvider rewraps twice: getLatestTagName produces
 * ERR_UPDATER_LATEST_VERSION_NOT_FOUND, and parseUpdateInfo then wraps that in
 * ERR_UPDATER_INVALID_RELEASE_FEED.
 */
const FEED_WRAPPER_CODES = new Set([
  'ERR_UPDATER_INVALID_RELEASE_FEED',
  'ERR_UPDATER_LATEST_VERSION_NOT_FOUND',
]);

/** The literal sentences those same two wrappers write into their message. */
const FEED_WRAPPER_PHRASES =
  /Cannot parse releases feed|Unable to find latest version on GitHub/;

/** Transient network shapes as they appear in NESTED stack text, not as a code. */
const TRANSIENT_CAUSE_PATTERNS = [
  /HttpError: (408|429|50\d)\b/,
  /\b(ECONNRESET|ETIMEDOUT|ENOTFOUND|EAI_AGAIN|ENETUNREACH|ECONNREFUSED)\b/,
];

/**
 * True when a releases-feed failure is a transient network blip wearing a
 * structural error's clothes.
 *
 * builder-util-runtime's newError() constructs a BRAND NEW Error and assigns
 * its own `code`, so electron-updater's double rewrap destroys the original
 * code: an HTTP 504 from the feed request arrives as
 * ERR_UPDATER_INVALID_RELEASE_FEED. That is why isTransientUpdaterError misses
 * these entirely - all six of its code branches test a code that no longer
 * exists, while its message branches still fire. The original failure survives
 * only as nested `e.stack` text inside the wrapper's message, so this reads the
 * message.
 *
 * Both halves must hold: the error is one of the two feed wrappers AND its text
 * carries a transient shape. A genuinely malformed feed has no transient shape
 * and stays loud, and a signature or checksum failure is not a feed wrapper at
 * all, so the structural cases stay reportable.
 *
 * The wrapper test accepts EITHER the code or the phrase. Requiring the code
 * would make this no-op in production if `code` is ever dropped between the
 * throw and the 'error' emit, while every unit test kept passing, since a test
 * sets `code` by hand. The phrase is written by the same wrapper that sets the
 * code, so it cannot drift away from it.
 *
 * Patterns are unanchored on purpose: the wrapper embeds the nested stack in
 * the MIDDLE of its own sentence, the same hazard BENIGN_RENDERER_ERRORS
 * documents for monaco.
 */
export function hasTransientNetworkCause(error: Error): boolean {
  const errorCode = (error as NodeJS.ErrnoException).code;
  const errorMessage = error.message ?? '';

  const isFeedWrapper =
    (errorCode !== undefined && FEED_WRAPPER_CODES.has(errorCode))
    || FEED_WRAPPER_PHRASES.test(errorMessage);
  if (!isFeedWrapper) return false;

  return TRANSIENT_CAUSE_PATTERNS.some((pattern) => pattern.test(errorMessage));
}

/**
 * The five values electron-updater can pass as the command name when it
 * elevates: the four LinuxUpdater.determineSudoCommand probes for on PATH,
 * plus the sudo fallback it returns when none is found.
 */
const ELEVATION_DENIED_PATTERN =
  /\bCommand (?:pkexec|gksudo|kdesudo|beesu|sudo) exited with code 12[67]\b/;

/**
 * True when a Linux install failed because the elevation prompt was denied,
 * rather than because the package manager itself failed.
 *
 * DebUpdater and RpmUpdater shell out to the system package manager through a
 * sudo front-end, and BaseUpdater.spawnSyncLog turns any non-zero exit into a
 * bare `Command <cmd> exited with code <n>` Error. That object carries no
 * `code` and no `cause`, so its message is the only thing there is to test.
 * That is also why this is a message pattern rather than a
 * UserConfigurationError subclass, against that class's own advice to extend
 * it instead: the throw site is third-party, so there is nothing to extend.
 *
 * Only 126 and 127 count, and pkexec(1) is what makes those two safe. It exits
 * 126 when the user dismissed the authentication dialog, and 127 when the user
 * is not authorized or authentication failed. Both mean the elevated command
 * never ran. When it does run, pkexec returns that program's own value, and
 * dpkg exits 1 or 2 while rpm exits 1, so a genuine install failure never
 * wears either code and stays reportable.
 *
 * Deliberate gap: sudo exits 1 on an authentication failure, and gksudo and
 * kdesudo exit 1 when cancelled, which is indistinguishable from a command
 * that ran and failed. Those declines are not suppressed. determineSudoCommand
 * resolves to pkexec on any current GNOME or KDE desktop, which is the case
 * that actually ships and the one this was written for.
 *
 * The pattern is unanchored for the reason benign-renderer-errors.ts
 * documents. Nothing is appended to this message today, so anchoring would
 * work, but the word boundaries survive an upstream reword that adds a prefix
 * or a suffix while still refusing to match `code 1267`.
 */
export function isElevationDeniedError(error: Error): boolean {
  return ELEVATION_DENIED_PATTERN.test(error.message ?? '');
}

/** The opening sentence of Squirrel.Mac's SQRLUpdaterErrorDomain read-only message. */
const READ_ONLY_VOLUME_PATTERN = /Cannot update while running on a read-only volume/;

/**
 * True when a macOS install failed because the app itself sits on a read-only
 * volume, which is what running it straight from the mounted DMG (or from a
 * translocated path) produces.
 *
 * DESKTOP-1A, 11 events from one install over two days and still arriving. It
 * is not a defect: the app cannot write over itself where the user put it, and
 * no build of ours would behave differently. It is also not transient, which is
 * why it gets a message in the app rather than only a counter - an install in
 * this state never updates again, silently, until someone moves it. See
 * `notifyReadOnlyVolume` below.
 *
 * Message-only, and for a harder reason than isElevationDeniedError's. That one
 * at least has JavaScript throwing it. This error is raised by Squirrel.Mac,
 * compiled into Electron, and only forwarded by JavaScript: MacUpdater's
 * constructor re-emits whatever `require("electron").autoUpdater` gives it. The
 * object arrives with no `code`, no `cause`, and no JS stack at all - the Sentry
 * event carries an empty frame list. The message is the only thing there is.
 *
 * Matching the first sentence rather than the whole paragraph is deliberate.
 * Squirrel appends a recovery suggestion that names Downloads, macOS Sierra, and
 * a GitHub issue URL, all of which are cosmetic and none of which identifies the
 * condition. Unanchored for the reason benign-renderer-errors.ts documents.
 */
export function isReadOnlyVolumeError(error: Error): boolean {
  return READ_ONLY_VOLUME_PATTERN.test(error.message ?? '');
}

/** strerror(EAGAIN), as macOS renders it into an NSError's description. */
const RESOURCE_UNAVAILABLE_PATTERN = /Resource temporarily unavailable/;

/**
 * True when an install failed with EAGAIN, which is transient wearing a name
 * none of the network classifiers above recognise.
 *
 * DESKTOP-1B. It reaches us by the same Squirrel.Mac forward as the read-only
 * error and is equally codeless, so isTransientUpdaterError's six errno branches
 * all miss it even though ECONNRESET and friends sit right beside EAGAIN in the
 * same errno table. The difference is only that this one arrived through macOS's
 * NSError rendering rather than through Node.
 *
 * The pattern deliberately ignores the sentence in front of it. macOS writes
 * `The operation couldn<U+2019>t be completed. <strerror>`, where the first half is
 * boilerplate that identifies nothing and carries a curly apostrophe no source
 * pattern should have to reproduce. `Resource temporarily unavailable` is the
 * strerror text, and it is the half that says EAGAIN.
 *
 * Testing the strerror alone makes this wider than "EAGAIN from Squirrel": a
 * feed wrapper whose nested stack text happens to carry the same phrase is
 * caught here too, one gate earlier than hasTransientNetworkCause would take
 * it. That is the right outcome either way, since both routes mean transient,
 * but the console line will name this gate rather than the feed one.
 */
export function isResourceUnavailableError(error: Error): boolean {
  return RESOURCE_UNAVAILABLE_PATTERN.test(error.message ?? '');
}

/** The sentence GitHubProvider writes when no feed entry matches the channel. */
const NO_PUBLISHED_VERSIONS_PATTERN = /No published versions on GitHub/;

/** The code the same provider attaches at the throw site that can reach us. */
const NO_PUBLISHED_VERSIONS_CODE = 'ERR_UPDATER_NO_PUBLISHED_VERSIONS';

/** A semver version carrying a prerelease component, e.g. `0.41.0-dev.1`. */
const PRERELEASE_VERSION_PATTERN = /^\d+\.\d+\.\d+-/;

/**
 * True when a PRERELEASE build found no release on its own channel, which is
 * that build's expected steady state rather than a failure.
 *
 * DESKTOP-17 arrived from a `0.41.0` prerelease build. AppUpdater's constructor
 * sets `allowPrerelease` from whether the running version has a prerelease
 * component, so a `-dev.1` build takes GitHubProvider's channel-matching loop
 * with `currentChannel = "dev"`. Every entry in the feed is a stable release,
 * so `hrefChannel` is null on all of them, neither the stable-fetch branch nor
 * the next-prerelease branch fires, `tag` stays null, and getLatestVersion
 * throws. We publish no such prerelease channel; there is nothing to ship.
 *
 * The prerelease conjunct is the whole point of this predicate, not a
 * belt-and-braces extra. GitHubProvider throws that same sentence from TWO
 * places. One is the tag-is-null throw above, which carries the code and is
 * reachable only when allowPrerelease is true. The other is the feed's own
 * `element("entry", ...)` lookup, which throws the identical sentence with NO
 * code when the Atom feed has zero entries. On a stable build that second one
 * means our releases feed is empty or broken, which is exactly the kind of
 * structural failure this file exists to keep loud. Requiring a prerelease
 * version is what separates them.
 *
 * `currentVersion` is a parameter rather than an `app.getVersion()` read inside
 * the body so the stable-build case is testable without faking Electron.
 *
 * The wrapper test accepts either the code or the phrase, the same disjunction
 * hasTransientNetworkCause uses and for the same reason: requiring the code
 * would make this a no-op in production if `code` is ever lost between the throw
 * and the emit, while every unit test that sets `code` by hand kept passing.
 */
export function isPrereleaseWithNoMatchingRelease(
  error: Error,
  currentVersion: string,
): boolean {
  if (!PRERELEASE_VERSION_PATTERN.test(currentVersion)) return false;

  const errorCode = (error as NodeJS.ErrnoException).code;
  return errorCode === NO_PUBLISHED_VERSIONS_CODE
    || NO_PUBLISHED_VERSIONS_PATTERN.test(error.message ?? '');
}

/**
 * The sentence the renderer toasts verbatim when the app cannot update because
 * of where it lives. Composed here rather than in the renderer for the reason
 * write-failure-notice.ts composes its own: the condition is main's to detect,
 * and the renderer has no channel through which to learn anything else about it.
 *
 * Squirrel's own text names Downloads, macOS Sierra and a GitHub issue. Ours
 * names the folder that fixes it and stops.
 */
const READ_ONLY_VOLUME_MESSAGE =
  'Kangentic cannot install updates while it runs from a read-only volume. '
  + 'Move Kangentic to your Applications folder to keep it up to date.';

/**
 * Tell the user, once per app run, that this install can never update itself.
 *
 * Latched for the reason write-failure-notice.ts latches: the condition is
 * permanent, so every check for the rest of the run rediscovers it. DESKTOP-1A
 * produced 11 events from one install, and without this flag it would produce 11
 * toasts. The latch is in memory and not persisted on purpose - a later launch
 * from the same read-only volume still cannot update, and the person who missed
 * one toast deserves to be told again rather than left wondering why the app
 * stopped updating.
 */
function notifyReadOnlyVolume(): void {
  if (readOnlyVolumeNoticeSent) return;
  // Latch on the SEND, not on reaching this function. On macOS every window can
  // be closed while the app keeps running, and a scheduled check landing in that
  // gap would otherwise consume the one notice this run gets and deliver it
  // nowhere. Arming only after a window actually received it means the next
  // check, once the dock icon has brought a window back, still tells the user.
  if (!updaterWindow || updaterWindow.isDestroyed()) return;
  updaterWindow.webContents.send(IPC.UPDATE_BLOCKED, READ_ONLY_VOLUME_MESSAGE);
  readOnlyVolumeNoticeSent = true;
}

/** @internal Exported for testing. */
export async function checkWithRetry(): Promise<void> {
  try {
    await autoUpdater.checkForUpdates();
  } catch {
    console.log('[UPDATER] Check failed, retrying in 30s...');
    checkRetrying = true;
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
    try {
      await autoUpdater.checkForUpdates();
    } catch (retryError) {
      console.error('[UPDATER] Check failed after retry:', retryError);
    } finally {
      checkRetrying = false;
    }
  }
}

/** @internal Exported for testing. */
export async function downloadWithRetry(): Promise<void> {
  try {
    await autoUpdater.downloadUpdate();
  } catch (firstError) {
    console.log('[UPDATER] Download failed, retrying in 30s:', firstError);
    downloadRetrying = true;
    try {
      await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
      await autoUpdater.downloadUpdate();
    } catch (retryError) {
      console.error('[UPDATER] Download failed after retry:', retryError);
    } finally {
      downloadRetrying = false;
    }
  }
}

/**
 * Registered on every path that bails out of updater init (dev, and a
 * packaged build with no update manifest). The renderer's updater surfaces
 * still exist on those paths, so without these `ipcRenderer.invoke` rejects
 * with `No handler registered` and surfaces as an unhandled rejection.
 */
function registerNoOpUpdaterHandlers(): void {
  ipcMain.handle(IPC.UPDATE_CHECK, () => {});
  ipcMain.handle(IPC.UPDATE_INSTALL, () => {});
}

/**
 * Initialize the auto-updater for packaged builds on every platform.
 *
 * Linux included: electron-updater ships DebUpdater / RpmUpdater alongside
 * AppImageUpdater, and its `autoUpdater` export selects between them by
 * reading the `package-type` marker electron-builder writes into
 * resourcesPath. Our fpm targets (deb, rpm) are both in electron-builder's
 * supportsAutoUpdate list, so each packaged Linux build already carries that
 * marker AND an app-update.yml, exactly like the NSIS and DMG builds.
 */
export function initUpdater(mainWindow: BrowserWindow): void {
  if (!app.isPackaged) {
    // The renderer's release-notes modal reaches `installUpdate()` from its
    // primary button, and the Developer tab can open that modal with fixture
    // notes in dev. Register no-ops so the invoke resolves instead of
    // rejecting with `No handler registered` (an unhandled rejection).
    // Dev only now - a packaged Linux build takes the real path below.
    registerNoOpUpdaterHandlers();
    return;
  }

  updaterWindow = mainWindow;
  // The read-only-volume notice is latched for the updater's lifetime, and
  // this is where that lifetime starts. In production initUpdater runs once
  // per app run, so this line is a no-op; it matters only in that it ties the
  // latch's scope to the thing that owns it rather than to the module.
  readOnlyVolumeNoticeSent = false;

  // electron-builder generates app-update.yml only when `--publish` is set,
  // so a misbuilt release (or a locally-packaged DMG/EXE without --publish)
  // can ship without it. Without this guard, electron-updater raises
  // ENOENT on every scheduled check and pollutes telemetry. Register
  // no-op IPC handlers so the renderer's "check for updates" UI does not
  // throw `No handler registered`, fire one telemetry event so we can
  // catch a recurrence in production, and bail before scheduling.
  if (!manifestExists()) {
    // No path in the line: it is a breadcrumb, and resourcesPath sits under the
    // user's home directory on a per-user Windows install.
    console.warn('[UPDATER] Skipping init: app-update.yml not found in the resources directory.');
    registerNoOpUpdaterHandlers();
    trackEvent('app_error', {
      source: 'updater',
      message: 'missing_manifest',
    });
    return;
  }

  autoUpdater.logger = updaterLogger;

  // We control the download -- don't auto-download on check
  autoUpdater.autoDownload = false;
  // Install pending updates silently when the user quits normally
  autoUpdater.autoInstallOnAppQuit = true;

  // Except on Linux, where "silently" is not available: DebUpdater and
  // RpmUpdater shell out to the system package manager, which always
  // elevates (LinuxUpdater.determineSudoCommand picks pkexec / gksudo /
  // kdesudo, falling back to sudo). On the quit path that surfaces a
  // password prompt as the window is disappearing, and the install races
  // the session teardown that is killing the process. Leave the update
  // staged instead: the release-notes modal's "Restart to update" is an
  // explicit, foreground moment where an auth prompt makes sense.
  // Upstream reached the same conclusion and made deferral the default for
  // these targets in a later major.
  if (process.platform === 'linux') {
    autoUpdater.autoInstallOnAppQuit = false;
  }

  // macOS differential download reads a cached update.zip from
  // ~/Library/Caches/<appId>-updater/pending/, which macOS evicts under
  // disk pressure. That race produces a bare `ENOENT: no such file or
  // directory, open '<path>'` error, historically our dominant updater
  // failure. Full redownload is an acceptable tradeoff for eliminating
  // the flakiness. See MacUpdater.js:88-103 for the cached-zip read
  // path we are bypassing.
  if (process.platform === 'darwin') {
    autoUpdater.disableDifferentialDownload = true;
  }

  // IPC handlers for renderer
  ipcMain.handle(IPC.UPDATE_CHECK, () => checkWithRetry());

  ipcMain.handle(IPC.UPDATE_INSTALL, () => {
    autoUpdater.quitAndInstall(true, true);
  });

  // When an update is available, start downloading immediately (with retry).
  autoUpdater.on('update-available', () => {
    console.log('[UPDATER] Update available, downloading...');
    void downloadWithRetry();
  });

  // When download completes, notify the renderer
  autoUpdater.on('update-downloaded', (info) => {
    // In the template, not a second argument: the breadcrumb policy drops
    // every string argument after the first.
    console.log(`[UPDATER] Update downloaded: ${info.version}`);
    if (updaterWindow && !updaterWindow.isDestroyed()) {
      updaterWindow.webContents.send(IPC.UPDATE_DOWNLOADED, {
        version: info.version,
        releaseNotes: normalizeReleaseNotes(info.releaseNotes),
      });
    }
  });

  // Log every error. Surface exactly one to the user: the read-only volume
  // (DESKTOP-1A), which is permanent and silent and would otherwise leave an
  // install frozen on its version with no explanation. Everything else stays
  // invisible, because there is nothing the user could do about it.
  //
  // Skip analytics during retry to avoid double-counting transient failures
  // that resolve on second attempt. Then filter the classes that are real but
  // un-actionable, so they do not pollute the issue stream.
  //
  // NOTE the two positions below, which are NOT interchangeable and are not
  // uniform in this handler today. A gate ABOVE trackEvent drops the Aptabase
  // count as well; a gate BELOW it keeps the count and drops only the Sentry
  // report. isTransientUpdaterError sits above, which predates the split and
  // was a deliberate choice at the time ("do not pollute app_error"). Every
  // gate added since sits below, on the argument that the volume view is worth
  // keeping. The consequence is worth knowing before reading the numbers: the
  // same network failure is counted or not depending on whether
  // electron-updater happened to rewrap it and destroy its errno, since the
  // rewrapped form falls to hasTransientNetworkCause below instead. Moving
  // isTransientUpdaterError down would make the file consistent, but it would
  // also redefine what app_error/updater has counted since 5513c7cc
  // (2026-04-16), so it is a telemetry decision rather than a cleanup.
  //
  // A NEW gate goes below trackEvent unless there is a reason to lose the count.
  autoUpdater.on('error', (error) => {
    console.error('[UPDATER] Error:', error);
    if (checkRetrying || downloadRetrying) return;
    // One preview for every branch below, so widening it (or routing it through
    // sanitizeErrorMessage) stays a one-line change rather than six.
    const errorPreview = error.message.slice(0, 80);
    if (isTransientUpdaterError(error)) {
      const errorCode = (error as NodeJS.ErrnoException).code;
      console.log('[UPDATER] Suppressing transient error telemetry:',
        errorCode ?? errorPreview);
      return;
    }
    trackEvent('app_error', {
      source: 'updater',
      message: sanitizeErrorMessage(error.message),
    });
    // A feed failure that is transient underneath its structural wrapper is
    // counted above but never filed as an issue: GitHub returned a 504 on a
    // routine check and the next check succeeds, so there is nothing to ship.
    //
    // This line's POSITION is load-bearing. Above trackEvent it would delete a
    // volume count that works today ("how often do update checks fail"), which
    // is the same split the missing-CLI exclusion makes inside
    // reportHandledError. Below the call it would do nothing at all.
    if (hasTransientNetworkCause(error)) {
      console.log('[UPDATER] Counting but not reporting a transient feed failure:',
        errorPreview);
      return;
    }
    // Same split, same reason, for the Linux install path: the user hit
    // "Restart to update" and then dismissed the polkit prompt. Counted, so
    // "how often is an update declined" stays answerable, but never filed,
    // because the user's own choice is not a defect we can ship a fix for.
    // This gate's position matters for exactly the reason above.
    if (isElevationDeniedError(error)) {
      console.log('[UPDATER] Counting but not reporting a denied elevation prompt:',
        errorPreview);
      return;
    }
    // The macOS install path's equivalent, and the one case here the user has
    // to hear about: the app is running from a read-only volume, so it cannot
    // write over itself and never will until someone moves it. Counted, never
    // filed, and unlike every other branch in this handler it also says so in
    // the app. Same position, same reason, as the two gates above.
    if (isReadOnlyVolumeError(error)) {
      console.log('[UPDATER] Counting but not reporting a read-only volume:',
        errorPreview);
      notifyReadOnlyVolume();
      return;
    }
    // EAGAIN, arriving through macOS's NSError rendering rather than through
    // Node, which is the only reason isTransientUpdaterError's errno branches
    // miss it. As transient as the network blips above and treated the same.
    if (isResourceUnavailableError(error)) {
      console.log('[UPDATER] Counting but not reporting a transient EAGAIN:',
        errorPreview);
      return;
    }
    // A prerelease build asking a feed that publishes no such channel. That is
    // the expected answer for that build, not a failure, so it is counted and
    // dropped. A STABLE build seeing the same sentence means our feed is empty,
    // which the predicate deliberately does not match and which still reports.
    if (isPrereleaseWithNoMatchingRelease(error, app.getVersion())) {
      console.log('[UPDATER] Counting but not reporting a prerelease with no matching release:',
        errorPreview);
      return;
    }
    // Handled, so Sentry's global handlers never see it; forward the real
    // error so structural updater failures are diagnosable, not just counted.
    reportHandledError(error, { source: 'updater' });
  });

  // Schedule checks
  checkTimeout = setTimeout(() => {
    console.log('[UPDATER] Checking for updates...');
    checkWithRetry();

    checkInterval = setInterval(() => {
      console.log('[UPDATER] Checking for updates...');
      checkWithRetry();
    }, CHECK_INTERVAL_MS);
  }, INITIAL_DELAY_MS);
}

/**
 * Update the window reference used by the auto-updater. Called when macOS
 * recreates the window after all windows were closed (dock icon click).
 */
export function updateUpdaterWindow(mainWindow: BrowserWindow): void {
  updaterWindow = mainWindow;
}

/**
 * Synchronously clear updater timers. Called from syncShutdownCleanup().
 */
export function stopUpdaterTimers(): void {
  if (checkTimeout) {
    clearTimeout(checkTimeout);
    checkTimeout = null;
  }
  if (checkInterval) {
    clearInterval(checkInterval);
    checkInterval = null;
  }
}
